'use client';
import './globals.css';
import './form.css';
// import type { Metadata } from 'next';
import RootStyleRegistry from '@/components/RootStyleRegistry';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RootStyleRegistry>
          <Header />
          {children}
          <Footer />
        </RootStyleRegistry>
      </body>
    </html>
  );
}
