'use client';
import './globals.css';
import './form.css';
// import type { Metadata } from 'next';
import RootStyleRegistry from '@/components/RootStyleRegistry';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RootStyleRegistry>
          <Header />
          {/* minus Header and Footer */}
          <div className="py-10 min-h-[calc(100vh-340px)]">{children}</div>
          <Footer />
        </RootStyleRegistry>
      </body>
    </html>
  );
}
